### ISSUE TITLE
Innovation Committee Meeting - Your Contribution

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Data-and-Domain-Models#1]
Add your topic suggestions for the _innovation committee_ meeting on Monay, 16.10.2017.

## Topic suggestions
- **Example topic**, created by `@`author
- ...

**Comment by RaphaelKomander** [comment]
- Schema Definition Language (SDL)

**Comment by zubairov** [comment]
@philecs what is the innovation committee?

**Comment by drobiazko** [comment]
It's a fancy name for our periodic meetings in Cologne.

**Comment by zubairov** [comment]
Nice... want a cool english names for other meetings too!
