### ISSUE TITLE
Add relation object for tasks

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Data-and-Domain-Models#100]
As a user, I want to create relations between tasks so that I can describe dependencies between them.

The idea is to add a relation object to be able to represent relations between different tasks, such as _blocked by_ or _is blocking_.

---

**Acceptance Criteria:**

- [x] Relation object idea has been approved or rejected
   - [x] In case of approvement: Relation object has been incroporated into the collaboration model

---

[**Definition of Done**](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/CONTRIBUTING.md#definition-of-done)

**Comment by plevie** [comment]
Test
