### ISSUE TITLE
Review Release Cylce part of versioning decision process

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Data-and-Domain-Models#104]
Review [**Release Cylce part**](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/MasterDataModels/Versioning/VersioningMasterDataModel.md#release-cycles) in order to secure appropriate release cycles for new model changes.

- [x] Create an issue for first release cycle improvement and comment all further improvements within this issue
---

**Acceptance Criteria:**

- [x] Feedback provided within workgroup call

---

[**Definition of Done**](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/CONTRIBUTING.md#definition-of-done)

**Comment by ealtendorf** [comment]
Perhaps we should find out, how often other open source projects publish releases?
e.g.:
https://about.gitlab.com/2015/12/17/gitlab-release-process/
