### ISSUE TITLE
Note down pitfalls (findings) about developing a proper component for the elastic iPaas platform

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#20]
Create FAQ section for creation of an adapter

**Comment by philecs** [comment]
We should write down issues that arised while developing the adapters & transformers to provide answers for recurring questions (FAQ section)

**Comment by philecs** [comment]
Create FAQ section for creation of an adapter

**Comment by philecs** [comment]
@shterion created a [FAQ Section](https://github.com/openintegrationhub/Connectors/blob/master/Adapters/FAQ.md)
