### ISSUE TITLE
Provide the actual JSONata expression file of Snazzy

### ISSUE THREAD

**Issue by RaphaelKomander** [openintegrationhub/Data-and-Domain-Models#46]
The use of [JSONata](https://github.com/openintegrationhub/Connectors/tree/Transformers/Transformer)

- [ ] Technical mapping between Snazzy Contacts & **[Standard Data Model - Address](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/schemes/address.json)**
- [ ] Technical mapping between Snazzy Contacts & **SilvERP**

**Comment by philecs** [comment]
Currently for person object
[JSONata snazzy to OIH](https://github.com/openintegrationhub/Connectors/blob/master/Transformer/src/JSONataSnazzyContactsToOIH.js)
[JSONata oih to snazzy](https://github.com/openintegrationhub/Connectors/blob/master/Transformer/src/JSONataOihToSnazzyContacts.js)
[JSONata oih to wice](https://github.com/openintegrationhub/Connectors/blob/master/Transformer/src/JSONataOihToWice.js)
