### ISSUE TITLE
Business Cases and Best Practices

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/Data-and-Domain-Models#85]
Provide business cases and best practices for the address-model to explain for example when to use the relations or the categories.

**Comment by philecs** [comment]
Initial file: https://github.com/openintegrationhub/Data-and-Domain-Models/blob/bestPractices/MasterDataModels/Addresses/UseCasesAndBestPractices.md

**Comment by philecs** [comment]
Next version uploaded. Changes from discussion incorporated.
