### ISSUE TITLE
JSON schemas for collaboration throw syntax errors

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Data-and-Domain-Models#97]
While validating the JSON schemas, some errors occured in several files e.g. _Expecting comma or }, not string_

I would suggest to use https://jsonformatter.curiousconcept.com/ to verify the JSON Schemas. **Note: Please notice that the validator can not validate the references.**

Examplary errors for [calendarevent.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/main/schema/collaboration/calendarevent.json):
- Line 21 : syntax error, Expecting comma or }, not string
- Line 41: Duplicated "definitions" 
- Line 59 : syntax error, Expecting comma or }, not string
- Line 70 : syntax error, Expecting comma or }, not string

Checklist:

- [x] Fix [calendarevent.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/main/schema/collaboration/calendarevent.json)
- [x] Fix [collaborationelement.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/main/schema/collaboration/collaborationelement.json)
- [x] Fix [email.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/main/schema/collaboration/email.json)
- [x] Fix [task.json](https://github.com/openintegrationhub/Data-and-Domain-Models/blob/master/src/main/schema/collaboration/task.json)

Acceptance Criteria:

- [x] All schmeas are successfully validated 
- [x] All schemas match best practices for JSON schemas
- [ ] Schemas match UML diagram logic

**Comment by philecs** [comment]
@Heimig  I found one more thing: "definitions" is duplicated within calendarevent.json. Should only use "definitions" once:

```
...
definitions":{
      "Contact":{  
         "type":"object",
         "properties":{  
            "name":{  
               "type":"string",
               "description":"Name of the contact",
               "examples":[  
                  "John Doe"
               ]
            },
            "eMail":{  
               "type":"string",
               "description":"E-mail of the contact",
               "examples":[  
                  "john.doe@email.com"
               ]
            }
         },         
		 "definitions":{  
            "Calendar":{  
               "type":"object",
...
```

Validator does not show this, because is is syntactically correct.

**Comment by Heimig** [comment]
@philecs Changed the .jsons and commited my changes.

**Comment by philecs** [comment]
@Heimig 

Changes look good to me. Just missing one more thing:

**Comment by Heimig** [comment]
@philecs 
I changed "Calendars" to be definition of the "Contacts" object. Added the property "Calendars" as array to "Contacts" to reflect the change.

**Comment by philecs** [comment]
@Heimig Had to make some further adjustments. 
Check out: [commits](https://github.com/openintegrationhub/Data-and-Domain-Models/compare/e5ecbfac14...723beb1df5) if you want to see the changes.

**Comment by philecs** [comment]
JSON Schemas fixed
